// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9IUlkNDR6vOtEM5tgO3jcWzxLluu-uRQ',
    appId: '1:1000634542070:web:6598131b11c291b074c9d7',
    messagingSenderId: '1000634542070',
    projectId: 'vend-25de9',
    authDomain: 'vend-25de9.firebaseapp.com',
    storageBucket: 'vend-25de9.appspot.com',
    measurementId: 'G-CZCGD0REJF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNIXS8uNtcTvRLtsCsRCxCCWQUa1vijLE',
    appId: '1:1000634542070:android:8a8758a17161a88674c9d7',
    messagingSenderId: '1000634542070',
    projectId: 'vend-25de9',
    storageBucket: 'vend-25de9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALOBa6KSTIbZicRXAhVs0VDUy0oylCyw8',
    appId: '1:1000634542070:ios:218e76fe51d57da874c9d7',
    messagingSenderId: '1000634542070',
    projectId: 'vend-25de9',
    storageBucket: 'vend-25de9.appspot.com',
    iosBundleId: 'com.example.xy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALOBa6KSTIbZicRXAhVs0VDUy0oylCyw8',
    appId: '1:1000634542070:ios:218e76fe51d57da874c9d7',
    messagingSenderId: '1000634542070',
    projectId: 'vend-25de9',
    storageBucket: 'vend-25de9.appspot.com',
    iosBundleId: 'com.example.xy',
  );
}
